#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
contour_points.py creates contour plot based on policies.csv file 
    (generated by policies.py)
Created on Tue Feb 20 07:29:14 2018

@author: peter
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_contour(LOWER_CRATE_LIM, UPPER_CRATE_LIM, chargetime, FINAL_CUTOFF, numpol, PULSE=0):
    
    # Import policies
    if PULSE:
        policies = np.genfromtxt('policies_withpulse'+ str(PULSE) + 'C_' + \
                                 str(80-FINAL_CUTOFF) + 'per_pulse.csv', delimiter=',')
    else:
        policies = np.genfromtxt('policies.csv', delimiter=',')
    
    OVERRIDE_AX_LIM = True
    
    if OVERRIDE_AX_LIM:
        LOWER_LIM = 2.4
        UPPER_LIM = 7.1
    else:
        margin = 0.2 # plotting margin
    
    # Calculate Q1(CC1, CC2) values for contour lines
    if OVERRIDE_AX_LIM:
        CC1 = np.arange(LOWER_LIM,UPPER_LIM,0.01)
        CC2 = np.arange(LOWER_LIM,UPPER_LIM,0.01)
    else:
        CC1 = np.arange(LOWER_CRATE_LIM-margin,UPPER_CRATE_LIM + margin,0.01)
        CC2 = np.arange(LOWER_CRATE_LIM-margin,UPPER_CRATE_LIM + margin,0.01)
    [X,Y] = np.meshgrid(CC1,CC2)
    Q1 = (100)*(chargetime - ((60*(FINAL_CUTOFF/100))/Y))/((60/X)-(60/Y))
    Q1[np.where(Q1<0)]  = float('NaN')
    Q1[np.where(Q1>FINAL_CUTOFF)] = float('NaN')
    #Q1_values = np.arange(5,76,10)
    
    ## Create contour plot
    ## Initialize plot 1: color = SOC1
    plt.figure() # x = CC1, y = CC2, contours = Q1
    plt.rcParams.update({'font.size': 16})
    plt.set_cmap('viridis')
    levels = np.flipud(np.arange(FINAL_CUTOFF,-1,-10))
    #levels[0] = 1
    levels[-1] = levels[-1] - 1
    C = plt.contour(X,Y,Q1,levels,zorder=1)
    plt.clabel(C, fontsize=12,fmt='%1.0f')
    if PULSE:
        plt.title('Pulse = ' + str(PULSE) + 'C for ' + str(80-FINAL_CUTOFF) + '% SOC; ' + str(numpol) + ' policies',fontsize=16)
    else:
        plt.title('Time to ' + str(FINAL_CUTOFF) + '% = ' + str(chargetime) + ' minutes; ' + str(numpol) + ' policies',fontsize=16)
    plt.xlabel('C1')
    plt.ylabel('C2')
    plt.axis('square')
    if OVERRIDE_AX_LIM:
        plt.xlim((LOWER_LIM,UPPER_LIM))
        plt.ylim((LOWER_LIM,UPPER_LIM))
    else:
        plt.xlim((LOWER_CRATE_LIM-margin, UPPER_CRATE_LIM+margin))
        plt.ylim((LOWER_CRATE_LIM-margin, UPPER_CRATE_LIM+margin))

    # Make full screen
    manager = plt.get_current_fig_manager()
    manager.window.showMaximized()
    
    ## PLOT POLICIES
    one_step = 60*(FINAL_CUTOFF/100)/chargetime;
    plt.scatter(one_step,one_step,c='k',marker='s',zorder=3) ## BASELINE
    if PULSE:
        plt.scatter(policies[:,2],policies[:,3],c='k',zorder=2)
    else:
        plt.scatter(policies[:,0],policies[:,1],c='k',zorder=2)
    
    ## SAVE FIGURE
    if PULSE:
        plt.savefig('contour_justpoints_' + str(PULSE) + 'C_' + str(80-FINAL_CUTOFF) + 'per_pulse.png', bbox_inches='tight')
    else:
        plt.savefig('contour_justpoints.png', bbox_inches='tight')